### ISSUE TITLE
TLSSocket.destroy() is not fully closing the socket

### ISSUE THREAD

**Issue by user447463** [joyent/node#9242]
node 0.12 seems to have introduced a timeout related issue for the TLS package. Closing the TLSSocket is not enough to stop the timeout but an additional TCP socket close is necessary.

Please see the following code sample for a reproducible pattern (0.10 vs. 0.12)

```
var url=require('url').parse(process.argv[2]);
var secure=url.protocol=='https:';

var socket=new require('net').Socket();

socket.setTimeout(2000, function() {
	this.destroy();
	console.log('TCP connection timed out');
});

socket.connect({ host: url.hostname, port: url.port || (secure?443:80) }, function() {
	if (secure)
	{
		require('tls').connect({ socket: this, rejectUnauthorized: false, servername: url.hostname }, function() {
			this.destroy();
			console.log('SSL successfully connected');
		}).on('error', function(error){
			this.destroy();
			console.log('Error during SSL handshake');
		});
	}
	else
	{
		this.destroy();
		console.log('Non-SSL successfully connected');
	}
}).on('error', function(error) {
	this.destroy();
	console.log('Error during TCP connection '+error.code);
});

// Dummy line to keep node from exiting
setInterval(function() {}, 1000);
```

Expected result
```
node file.js https://www.google.com
SSL successfully connected
```

Actual result
```
node file.js https://www.google.com
SSL successfully connected
TCP connection timed out
```

**Comment by user447463** [comment]
In case it is of any help, the issue seems to have started with 0.11.3.

**Comment by user447463** [comment]
For cross-reference, the respective bug at io.js
https://github.com/iojs/io.js/issues/878

**Comment by indutny** [comment]
Should be fixed by https://github.com/iojs/io.js/pull/891

**Comment by indutny** [comment]
See https://github.com/iojs/io.js/commit/9b6b05556f7684db396376f682f8042685a5b2b6 for a fix.

**Comment by trevnorris** [comment]
Thanks @indutny. Landed the same on bada87bd666f.

**Comment by jadbaz** [comment]
So has this been resolved or not?
I'm on node 4.0.0 and I still have this issue.
client.destroy simply does not work.

This is my code:

```
var client = new require('net').Socket();
client.connect(54321, '192.168.1.7', ()=>{
    client.write("Hello");
    client.destroy();
    process.exit();
});
```

I'm using [Hercules](http://www.hw-group.com/products/hercules/index_en.html) to test it.
I get: `5:19:24 PM:  192.168.1.21 Client connected`
The program exits and I don't get a disconnected message.

If this has been fixed or I'm wrong please tell me. If this is indeed a bug, I'll open a new issue for Node 4.0.0
